### ISSUE TITLE
Integration was working then stopped

### ISSUE THREAD

**Issue by willbiker** [wills106/homeassistant-solax-modbus#240] opened 2022-12-12 20:08 UTC
Hi! I had wills modbus integration up and running pulling in registers and data nicely to my HA. Then it randomly stopped and I got an error saying inverter serial number can't be found. I updated HA and also updated the integration with no luck. I then deleted the integration and reinstalled with no luck. I fixed the ip of my inverter so it can't change and I can still ping it. Any ideas how I can get this working. Here is the log below.

Thanks in advance

Will
![Screenshot_20221212-195720](https://user-images.githubusercontent.com/117373918/207144207-f9988c79-e136-4ec2-ba12-78c60b310f91.png)

**Comment by infradom** [comment] 2022-12-12 22:04
One possibility: The inverter was probably already asleep when you reinstalled
Maybe it will work again when there is PV

**Comment by Patrik1973** [comment] 2022-12-13 08:49
> Hi! I had wills modbus integration up and running pulling in registers and data nicely to my HA. Then it randomly stopped and I got an error saying inverter serial number can't be found. I updated HA and also updated the integration with no luck. I then deleted the integration and reinstalled with no luck. I fixed the ip of my inverter so it can't change and I can still ping it. Any ideas how I can get this working. Here is the log below.
> 
> Thanks in advance
> 
> Will ![Screenshot_20221212-195720](https://user-images.githubusercontent.com/117373918/207144207-f9988c79-e136-4ec2-ba12-78c60b310f91.png)

I don't think so, it isn't that inverter is sleeping...I have the same issue, the same errors and my inverter produce power.
In HA at the devices integration shows 4 entities only.

**Comment by infradom** [comment] 2022-12-13 09:28
@Patrik1973 Even though your problem looks similar, it is probably not the same. The @willbiker log shows that the system tried to awake the inverter "cannot wakeup inverter" so it was asleep. In the current version, we still have issues with waking up an inverter automatically, so that part does not work yet.

**Comment by infradom** [comment] 2022-12-13 09:31
@Patrik1973 In most cases, the system being unable to read the serial number is caused by bad wiring or bad ip addres/port configuration issues.
Were you able to communicate with the inverter in the past from within this integration?

**Comment by infradom** [comment] 2022-12-13 09:41
Correction @Patrik1973 : I see in other posts your system worked with previous versions. Sorry ...

**Comment by Patrik1973** [comment] 2022-12-13 09:41
@infradom Yes, on saturday the integration was stopped and shows 4 entities only, then I tried to reinstall it few times and situations is the same still.
At the attachment you can see many errors.

https://github.com/wills106/homeassistant-solax-modbus/issues/234#issuecomment-1345501318
[Modbus Error.txt](https://github.com/wills106/homeassistant-solax-modbus/files/10216526/Modbus.Error.txt)

**Comment by infradom** [comment] 2022-12-13 09:45
@Patrik1973 It is important that you install the integration when the inverter is awake
So you may need to remove / restart / reinstall at a proper time when the inverter is awake
Maybe you already tried that
In the mean time, I am examining your log ...

**Comment by Patrik1973** [comment] 2022-12-13 09:48
@infradom Yes I know it, I did it...ok I will try it again.
I have on HA last version installed and on integration SOLAX modbus I have 2022.12.4 version

**Comment by willbiker** [comment] 2022-12-13 09:55
Hi All, Thanks for the comments! Indeed the inverter status doesn't seem to make a difference. The IP is fixed and I can ping is so there should be no issues with connectivity as it worked  few weeks ago flawlessly. I am using the wifi dongle which the description said isn't supported however as as mentioned, it was working fine. Maybe I need to get an ethernet adapter instead

**Comment by infradom** [comment] 2022-12-13 10:01
Ok, I get it .. We really have problems with the wifi dongle. I personally prefer not to put any efforts in debugging systems that try to use modbus over pocketwifi (or pocketlan). It is simply unpredictable.

**Comment by infradom** [comment] 2022-12-13 10:06
@Patrik1973 Do you also connect through  a pocketwifi adapter? If so, sorry that explains a lot, but I cannot help you then ..
Have you submitted the details of your installation ? type of inverter, connection method, ... ? I did not find it in either thread

**Comment by willbiker** [comment] 2022-12-13 10:07
Sure understood. So an ethernet dongle may be the answer for me, worth a try.

I think the 'cannot wake' error may have been as a result of me pressing the 'unlock' button. I will invest in an ethernet dongle and will try again

Thanks

**Comment by willbiker** [comment] 2022-12-13 10:12
I assume an ethernet dongle is needed for ethernet connection for the x1 Hybrid inverters? There is no built in network port I assume? What method of network connection do you use?

**Comment by infradom** [comment] 2022-12-13 10:14
@willbiker  : Not an Ethernet (pocketlan) dongle, that wont work either but a modbus RS485 to Eth like https://www.waveshare.com/wiki/RS485_TO_ETH_(B)
Our wiki descirbes this

**Comment by wills106** [comment] 2022-12-13 10:14
Have a look in the Wiki for the list of supported RS485 - Ethernet adaptors.
Take note of the unworking / unreliable section below.

**Comment by Patrik1973** [comment] 2022-12-13 10:22
Yes, I also use the wifi pocket adapter, ok, if also LAN adapter is not supported made from Solax I will try to change a connection to other.

I'm sorry for my issues...las week I started PV and tried the integration and everything seems ok and suddenly everything failed.

My configuration is Solax X3 G4

**Comment by infradom** [comment] 2022-12-13 10:27
@Patrik1973 In the future I might develop a HA addon that converts serial RS485 modbus to TCP based modbus. That would remove the need for an external converter, a simple low cost USB-RS485 dongle would then be suffient. Unfortunately, I have a big backlog and need to do other things first. For my Gen4 X3: I use the Waveshare  RS485 to ETH (B) converter

**Comment by Patrik1973** [comment] 2022-12-13 10:33
@infradom Thanks a lot for your advice, the fastest for me if I order the Waveshare RS485 to LAN (B) converter.

**Comment by wills106** [comment] 2022-12-13 10:36
If your switch supports POE there is a POE version. Saves needing to supply power to it.

**Comment by willbiker** [comment] 2022-12-15 14:16
Hi Again.  I'm trying to learn all about integrating to my inverter using RS485 and converters. The Waveshare RS485 TO ETH (B) looks to be a reliable but what does the ethernet output connect to? I run HA on a RPi4, do I connect the eithernet directly to the RPI or to my router for a connection through the network?

My RPI can be moved next to my Inverter, would a RS485 TO USB, plugged directly into my RPI work also?

Thanks

Will

**Comment by wills106** [comment] 2022-12-15 14:25
Either a Waveshare RS485 TO ETH (B) plugged in to your router or RS485 to USB adaptor plugged directly to your RPI will work fine.
Just depends on which is easier to install.
RS485 to USB is the cheapest option, just take note of [No 2](https://github.com/wills106/homeassistant-solax-modbus#known-issues) you can filter those out if you configure your logger correct I believe.

**Comment by wills106** [comment] 2022-12-17 12:39
Closing down as Issue related to Pocket WiFi.

If you have further issues when you get an RS485 - Ethernet / USB adaptor then feel free to raise a new issue.

**Closed by wills106** 2022-12-17 12:39 UTC
