### ISSUE TITLE
[Bug]: Detected blocking call to import Module

### ISSUE THREAD

**Issue by kistelek2** [wills106/homeassistant-solax-modbus#902] opened 2024-05-18 20:09 UTC
### Describe the bug

Logger: homeassistant.util.loop
Source: util/loop.py:99
First occurred: 17 May 2024 at 18:12:51 (1 occurrences)
Last logged: 17 May 2024 at 18:12:51

Detected blocking call to import_module inside the event loop by custom integration 'solax_modbus' at custom_components/solax_modbus/__init__.py, line 143: plugin = importlib.import_module( (offender: /config/custom_components/solax_modbus/__init__.py, line 143: plugin = importlib.import_module(), please create a bug report at https://github.com/wills106/homsassistant-solax-modbus/issues

### Integration Version

2024.05.3

### Homeassistant core version

2024.5.4

### Inverter brand

Solax G3X4

### Plugin used

plugin_solax.py

### Serial prefix

H34A10

### Inverter firmware versions

0

### Connection Method

Waveshare

### Dongle firmware

0

### Detailed Error Log

Logger: homeassistant.util.loop
Source: util/loop.py:99
First occurred: 17 May 2024 at 18:12:51 (1 occurrences)
Last logged: 17 May 2024 at 18:12:51

Detected blocking call to import_module inside the event loop by custom integration 'solax_modbus' at custom_components/solax_modbus/__init__.py, line 143: plugin = importlib.import_module( (offender: /config/custom_components/solax_modbus/__init__.py, line 143: plugin = importlib.import_module(), please create a bug report at https://github.com/wills106/homsassistant-solax-modbus/issues

### Additional context

Seems to be working but says to log a bug so here we are.

**Comment by wills106** [comment] 2024-05-19 06:27
This is a duplicate of #876 which is fixed in [2024.05.4](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.05.4)

**Closed by wills106** 2024-05-19 06:27 UTC
Labels: bug, solax
