### ISSUE TITLE
Custom integration won't load with 2023.9 & 2023.9.1

### ISSUE THREAD

**Issue by jamespreedy** [wills106/homeassistant-solax-modbus#528] opened 2023-09-10 08:07 UTC
**Describe the bug**
The integration worked fine immediately after 2023.9 was released on Wednesday.
On Thursday I noticed that my Solax device went dead and all my entities went unavailable.
Rebooting the host brought it back to life. 2023.9.1 came out yesterday and the integration now won't load at all.

![Screenshot 2023-09-10 at 8 56 57 am](https://github.com/wills106/homeassistant-solax-modbus/assets/559531/9c677aa3-c888-41dc-bfde-f636397ee7c5)

![Screenshot 2023-09-10 at 8 57 04 am](https://github.com/wills106/homeassistant-solax-modbus/assets/559531/8aa1043a-9c31-4d74-b062-7dc970310eb8)

**Mandatory details**
1. Integration Version: 2023.9.3
2. HA Version: 2023.9.1
3. Inverter Brand: SolaX
4. Plugin Used: SolaX
5. First 6 digits of Serial: H34A10
6. Connection Method: Waveshare RS485 to Eth

**Detailed Error Log**

```
Logger: homeassistant.setup
Source: loader.py:826 
First occurred: 5:56:58 am (1 occurrences) 
Last logged: 5:56:58 am

Setup failed for custom integration solax_modbus: Unable to import component: Exception importing custom_components.solax_modbus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/solax_modbus/__init__.py", line 31, in <module>
    from pymodbus.payload import BinaryPayloadBuilder, BinaryPayloadDecoder, Endian
  File "/usr/local/lib/python3.11/site-packages/pymodbus/payload.py", line 28, in <module>
    class BinaryPayloadBuilder:
  File "/usr/local/lib/python3.11/site-packages/pymodbus/payload.py", line 42, in BinaryPayloadBuilder
    self, payload=None, byteorder=Endian.Little, wordorder=Endian.Big, repack=False
                                  ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: Little

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 826, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.solax_modbus
```

**Additional context**
This custom component has been *flawless* since setting it up. Nothing I'm aware of has changed from a physical install perspective, and the Waveshare still has the blue connected light on it.

I believe there were a bunch of Modbus changes to HA 2023.9?

I also have a Nilan MVHR which also connects via Modbus (same Waveshare RS485 to Eth) - the custom integration for this also went dead following the 2023.9 HA update.

Appreciate this might be broken on the HA side, but just wanted to make sure I was reporting it. If there is any further information I can get for you to help resolve this, please let me know. 🍺

**Comment by infradom** [comment] 2023-09-10 08:46
I did an upgrade on my system to 2023.9.1, it went without problems. I did not go through the setup procedure though. I will also remove the integration and redo the setup to see whether the error is in that area.
I have no other integration that uses modbus, this might explain the difference.

**Comment by mstefany** [comment] 2023-09-10 09:32
Might be related to this change? https://github.com/pymodbus-dev/pymodbus/pull/1743/files

**Comment by wills106** [comment] 2023-09-10 11:16
Just released a new Beta, renamed all the Big / Little to BIG/LITTLE also updated pymodbus to 3.5.1 a per HA 2023.9.x

[2023.09.4b1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.09.4b1) could someone try it and let me know?

**Comment by eklofmar** [comment] 2023-09-10 12:36
I just updated to the beta and restarted the system. I still get the same error.

**Comment by wills106** [comment] 2023-09-10 12:40
I was on HA 2023.8.4 and this beta worked fine, just gone to 2023.9.1 and wont even read my serial. But no errors either...

**Comment by eklofmar** [comment] 2023-09-10 12:43
On HA 2023.8.4 it worked fine. 

After updated to the beta I got reading error. And after system restart it wont load.

**Comment by infradom** [comment] 2023-09-10 13:44
New version gives me this error:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solax_modbus/__init__.py", line 109, in async_setup_entry
    plugin = importlib.import_module(f".plugin_{plugin_name}", 'custom_components.solax_modbus')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/solax_modbus/plugin_solax.py", line 5389, in <module>
    order16 = Endian.BIG,
              ^^^^^^^^^^
AttributeError: type object 'Endian' has no attribute 'BIG'

**Comment by wills106** [comment] 2023-09-10 13:50
@infradom is your pyModbus on less than 3.5.x ?
I have updated mine to 3.5.1 and it doesn't complain it has no attribute.

It just can't read the serial and gives no feedback.

**Comment by wills106** [comment] 2023-09-10 15:02
Just so people know this isn't fixed yet and might take a day or two as there isn't anything obviously wrong.

If you don't use the HA Modbus for anything then HA 2023.9.1 and Integration 2023.09.3 works ok as it downgrades pyModbus to 3.3.1.

If you need to use the HA Modbus in addition to this Integration you need to stay on Ha 2023.8.x

**Comment by wartungsmonteur** [comment] 2023-09-12 05:13
Guten Morgen

Ich hatte das selbe Problem. Lösung war der komplette Neustart des Home-Assistenten und ganz untenvheraus und ein Neustart des waveshare Moduls, also stromlos diesen machen und neu starten. Nach dem Neustart eventuell das Addon händisch neu laden lassen.

**Comment by uspino2** [comment] 2023-09-12 06:17
Same thing here (not working), my errors are: 

```
Growatt_Modbus: reading firmware number from address 0x9 failed; other address may succeed
Growatt_Modbus: reading firmware number from address 0xbb9 failed; other address may succeed
Growatt_Modbus: cannot find firmware version, even not for other Inverter
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Failed to connect[ModbusTcpClient(10.10.10.126:502)]
```

Thanks.

**Comment by mudshurko** [comment] 2023-09-12 13:31
same problem since Sept.07
resetted the system today to :
 Home Assistant 2023.8.4 Supervisor 2023.08.3 Operating System 10.5 Frontend 20230802.1 - latest 
and installed Solax Inverter Modbus completly new
no effect
1 device, 4 entities....
I hope wills can find the problem...
lg

**Comment by wartungsmonteur** [comment] 2023-09-12 13:51
Das Addon ist ok. Man muss die neueste Version vom HA installieren, dann Solax via HACS updaten und das komplette System neu starten. Ich musste zudem die waveshare Module kurz vom Stromnetz trennen und neu booten lassen. Danach ging alles wieder ohne Probleme 
![Screenshot_20230912_154814_Home Assistant](https://github.com/wills106/homeassistant-solax-modbus/assets/131309361/724d87f9-c481-4f7c-954e-60a77fed4af2)
![Screenshot_20230912_154713_Home Assistant](https://github.com/wills106/homeassistant-solax-modbus/assets/131309361/9c2e7ad5-3861-4b1e-8863-211d560ebd3c)
![Screenshot_20230912_154631_Home Assistant](https://github.com/wills106/homeassistant-solax-modbus/assets/131309361/e2362cd7-3408-4244-9288-3e772393ef82)
![Screenshot_20230912_154607_Home Assistant](https://github.com/wills106/homeassistant-solax-modbus/assets/131309361/21639a82-728e-4990-8493-4fb575f74060)

**Comment by wartungsmonteur** [comment] 2023-09-12 13:53
![Screenshot_20230912_154542_Home Assistant](https://github.com/wills106/homeassistant-solax-modbus/assets/131309361/2173ebd4-6f9c-46bb-9862-44d0b49fc4fd)

**Comment by wartungsmonteur** [comment] 2023-09-12 13:55
Das Addon ist ok. Man muss die neueste Version vom HA installieren, dann Solax via HACS updaten und das komplette System neu starten. Ich musste zudem die waveshare Module kurz vom Stromnetz trennen und neu booten lassen. Danach ging alles wieder ohne Probleme.
![Uploading Screenshot_20230912_154814_Home Assistant.jpg…]()

**Comment by wartungsmonteur** [comment] 2023-09-12 13:55
![Screenshot_20230912_154542_Home Assistant](https://github.com/wills106/homeassistant-solax-modbus/assets/131309361/e53c1d72-1dac-47e7-ab5f-12acf32edde4)

**Comment by wartungsmonteur** [comment] 2023-09-12 13:56
Das Addon ist ok. Man muss die neueste Version vom HA installieren, dann Solax via HACS updaten und das komplette System neu starten. Ich musste zudem die waveshare Module kurz vom Stromnetz trennen und neu booten lassen. Danach ging alles wieder ohne Probleme.
![Screenshot_20230912_154814_Home Assistant](https://github.com/wills106/homeassistant-solax-modbus/assets/131309361/a3de4f1f-e3ca-4bd3-b1ee-4f8bdbe38cfe)
![Screenshot_20230912_154713_Home Assistant](https://github.com/wills106/homeassistant-solax-modbus/assets/131309361/631f6ba8-9b00-4bf8-abc2-97845644bfcc)
![Screenshot_20230912_154631_Home Assistant](https://github.com/wills106/homeassistant-solax-modbus/assets/131309361/4dd24fd8-9b39-47c5-aa43-0d5be03633de)
![Screenshot_20230912_154542_Home Assistant](https://github.com/wills106/homeassistant-solax-modbus/assets/131309361/b5939ed7-5b72-4e18-8a20-d7514c40c7c3)

**Comment by uspino2** [comment] 2023-09-12 14:12
> Das Addon ist ok. Man muss die neueste Version vom HA installieren, dann Solax via HACS updaten und das komplette System neu starten. Ich musste zudem die waveshare Module kurz vom Stromnetz trennen und neu booten lassen. Danach ging alles wieder ohne Probleme. ![Screenshot_20230912_154814_Home Assistant](https://user-images.githubusercontent.com/131309361/267353377-a3de4f1f-e3ca-4bd3-b1ee-4f8bdbe38cfe.jpg) ![Screenshot_20230912_154713_Home Assistant](https://user-images.githubusercontent.com/131309361/267353385-631f6ba8-9b00-4bf8-abc2-97845644bfcc.jpg) ![Screenshot_20230912_154631_Home Assistant](https://user-images.githubusercontent.com/131309361/267353391-4dd24fd8-9b39-47c5-aa43-0d5be03633de.jpg) ![Screenshot_20230912_154542_Home Assistant](https://user-images.githubusercontent.com/131309361/267353396-b5939ed7-5b72-4e18-8a20-d7514c40c7c3.jpg)

Restarting, power cycle, etc did not work me

**Comment by wartungsmonteur** [comment] 2023-09-12 14:27
Hast du auch mal die waveshare stromlas gemacht ?

**Comment by uspino2** [comment] 2023-09-12 14:35
> Hast du auch mal die waveshare stromlos gemacht ?
> Have you ever de-energised the waveshare?

Yes, left it unplug for a few minutes

**Comment by wartungsmonteur** [comment] 2023-09-12 15:08
Welche LED Leuchten ? 1 x Rot und 2 x Blau ?
Wenn ja, das Addon neu laden. Ich hatte auch dies Probleme. Bestimmt fünf Mal neu gestartet und irgendwann ging es plötzlich.

**Comment by mudshurko** [comment] 2023-09-12 16:36
fine when the system with the waveshare is working
(what is this waveshare exactly?)
I get data from the Solax X3 from COM port, using an USB - RS485 Konverter
the raspi is a Raspberry Pi 3
and this doesnt work now
yesterday i set up a new system, new image on a new SD-card, but nothing changed
it looks like a blocked Modbus transfer
HA gets no entities and no data
now I'm back on the "old" SD card, 
re-started for many times, no effect

**Comment by wartungsmonteur** [comment] 2023-09-12 16:44
Hallo
Ich nutze diesen waveshare
![20230912_184334](https://github.com/wills106/homeassistant-solax-modbus/assets/131309361/27ecdc97-52d2-4c55-b5af-aa388d6449cb)

**Comment by mudshurko** [comment] 2023-09-12 16:52
hmmm
this is serial to TCP
not USB - RS485
maybe the problem occurs in /dev/ttyUSB0 ?

**Comment by uspino2** [comment] 2023-09-13 05:17
HA just released 2023.9.2 but the problem is still there. [Release notes](https://github.com/home-assistant/core/pull/99988) say the update includes

```
Bump pymodbus to v3.5.2
Bump version, due to a connect problem, that is causing problems for the modbus integration
```

Hopefully this helps find the issue with Solax integration. Any update on the work @wills106 ? Thanks.

**Comment by filipi992062** [comment] 2023-09-13 05:57
I updated to Home assistant 2023.9.2 this morning and the problem was solved.

**Comment by uspino2** [comment] 2023-09-13 06:06
> I updated to Home assistant 2023.9.2 this morning and the problem was solved.

@filipi992062 Are you on Solax 2023.09.3 or 2023.09.4b1?

**Comment by wills106** [comment] 2023-09-13 06:47
> Hopefully this helps find the issue with Solax integration.

Updating pyModbus to 3.5.2 with Integration 2023.09.4b1 didn't help. When you add the Integration it fails to find a serial Number and doesn't give any feedback as to what's failed. I'll need to add in more debugging when I can.

> I updated to Home assistant 2023.9.2 this morning and the problem was solved.

Didn't get chance to update to 2023.9.2 this morning. If you are on Integration 2023.09.3 and not using the built in Modbus component the Integration could have downgraded pyModbus to 3.3.1

If you use `pip list` in your HA container it will list all the python modules and their versions.

**Comment by jamespreedy** [comment] 2023-09-13 07:14
Not sure what help I am here, but perhaps just as FYI.
I updated to HA 2023.9.2 this morning too.
I'm still running SolaX 2023.9.3.

I don't use the native HA modbus component (modbus: isn't in my configuration.yaml)

I get the below error in my logs.

`This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/solax_modbus/__init__.py:31 
Integration: solax_modbus (documentation, issues) 
First occurred: 7:06:14 am (1 occurrences) 
Last logged: 7:06:14 am

Unexpected exception importing component custom_components.solax_modbus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/solax_modbus/__init__.py", line 31, in <module>
    from pymodbus.payload import BinaryPayloadBuilder, BinaryPayloadDecoder, Endian
  File "/usr/local/lib/python3.11/site-packages/pymodbus/payload.py", line 28, in <module>
    class BinaryPayloadBuilder:
  File "/usr/local/lib/python3.11/site-packages/pymodbus/payload.py", line 42, in BinaryPayloadBuilder
    self, payload=None, byteorder=Endian.Little, wordorder=Endian.Big, repack=False
                                  ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: Little
`

and I also get

`Logger: homeassistant.setup
Source: loader.py:826 
First occurred: 7:06:14 am (1 occurrences) 
Last logged: 7:06:14 am

Setup failed for custom integration solax_modbus: Unable to import component: Exception importing custom_components.solax_modbus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/solax_modbus/__init__.py", line 31, in <module>
    from pymodbus.payload import BinaryPayloadBuilder, BinaryPayloadDecoder, Endian
  File "/usr/local/lib/python3.11/site-packages/pymodbus/payload.py", line 28, in <module>
    class BinaryPayloadBuilder:
  File "/usr/local/lib/python3.11/site-packages/pymodbus/payload.py", line 42, in BinaryPayloadBuilder
    self, payload=None, byteorder=Endian.Little, wordorder=Endian.Big, repack=False
                                  ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: Little

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 826, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.solax_modbus
`

![Screenshot 2023-09-13 at 8 10 54 am](https://github.com/wills106/homeassistant-solax-modbus/assets/559531/6e2bfaa4-8088-4eac-a9e4-99655d472ffc)


I also use modbus via another custom component (https://github.com/veista/nilan) for my Nilan MVHR.
Its still not working since me upgrading to HA 2023.9.x, with pretty similar symptoms.

Given that I don't use native HA modbus, and just these custom components, which both died at the same time, I'm not thinking it's a coincidence ... 🤞🏻

@wills106 - as always, thanks so much of your ongoing effort and support with this custom component - really appreciate it! 🍺

**Comment by PutoPunko** [comment] 2023-09-13 08:02
Hi,

Updated to HA 2023.9.2 with SolaX 2023.09.4b1 (connected to inverter directly to ETH port) and works OK (I am using as well HA modbus integration for other devices).

Best regards,

**Comment by uspino2** [comment] 2023-09-13 09:45
For me, HA 2023.9.2 works with Solax 2023.9.3, but not with 2023.9.4b1...

**Comment by uspino2** [comment] 2023-09-13 09:52
> If you use `pip list` in your HA container it will list all the python modules and their versions.

My Home Assistant is a VM (Hyper-X). How can I check modules version?

**Comment by alienatedsec** [comment] 2023-09-13 10:26
> > If you use `pip list` in your HA container it will list all the python modules and their versions.
> 
> 
> 
> My Home Assistant is a VM (Hyper-X). How can I check modules version?
> 
> 

@uspino2 you need to install the Advanced SSH & Web Terminal addon and can do anything as you would via normal putty connection

**Comment by PutoPunko** [comment] 2023-09-13 10:32
> Hi,
> 
> Updated to HA 2023.9.2 with SolaX 2023.09.4b1 (connected to inverter directly to ETH port) and works OK (I am using as well HA modbus integration for other devices).
> 
> Best regards,

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/98017018/77151ab7-ac9e-4d6b-95d1-dd97e89a78b3)

**Comment by uspino2** [comment] 2023-09-13 10:35
> > > If you use `pip list` in your HA container it will list all the python modules and their versions.
> > 
> > 
> > My Home Assistant is a VM (Hyper-X). How can I check modules version?
> 
> @uspino2 you need to install the Advanced SSH & Web Terminal addon and can do anything as you would via normal putty connection

Thanks, I tried that, but I get:

![Screenshot 2023-09-13 at 12 35 07 PM](https://github.com/wills106/homeassistant-solax-modbus/assets/24617436/cee379fd-781e-4f2c-9acb-e466c554449d)

**Comment by wills106** [comment] 2023-09-13 16:32
It's a bit more complicated on HAOS and I haven't used it in ages, but you need to check in the equivalent of the core container.
There should be a lot more python packages showing like:

![image](https://github.com/wills106/homeassistant-solax-modbus/assets/18155231/c6227770-53ad-4c32-b8c6-dcb61a79a6e4)

**Comment by wills106** [comment] 2023-09-13 17:11
Just released [2023.09.4b2](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.09.4b2) I think I have found why 2023.09.b1 was failing, there was another change in pyModbus 3.4.0.

I can confirm that forcing pyModbus to 3.5.2 on HA 2023.9.2 but not using the built in HA Modbus is working for me on 2023.09.4b2. The likes of @jamespreedy @mstefany are probably best confirming before I release a stable version as it looks they they are using this Integration in addition to the built in HA Modbus?

**Comment by jamespreedy** [comment] 2023-09-13 17:55
@wills106 - hey mate, thank you for all you help! We all owe you a beer for this one lol.

Just reading your comment above - I don't understand this all at the best of times, but I don't *think* that I'm using built in HA Modbus? I don't have  "modbus: " in my configuration.yaml - is that what you meant?

**Comment by jamespreedy** [comment] 2023-09-13 17:59
On that note, I've just pulled and tried beta 2 - still getting the same error I mentioned in this other bug - https://github.com/wills106/homeassistant-solax-modbus/issues/530. Think I've broken something by uninstalling and re-installing. 🤦🏻‍♂️🤦🏻‍♂️🤦🏻‍♂️

**Comment by wills106** [comment] 2023-09-13 17:59
Sorry I misread thinking your Nilan MVHR was using the built in HA Modbus, but I just reread it and you mentioned using another Integration for it.

**Comment by wills106** [comment] 2023-09-13 18:05
I think the best way would be to:

Remove Integration from Integration page.
Remove SolaX Modbus from HACS.
Ensure solax_modbus folder is no longer in custom_components
Restart HA
Download SolaX through HACS
Restart HA
Add SolaX Modbus on the Integration Page.

**Comment by wills106** [comment] 2023-09-13 18:25
For anyone trying Integration 2023.09.4b2, there is two potential errors I have not check for if you are still on pyModbus 3.3.1 or earlier:

'slave=slave'
or
'Endian.BIG' / 'Endian.LITTLE'

I might need to drop legacy support for pyModbus and HA as we will potentially have 3 main variations:
pyModbus 2.5.3,
pyModbus 3.0.x-3.3.1
pyModbus 3.5.x and above

I'll perform testing on Integration 2023.09.4b2 and pyModbus 3.3.1 in the next day or two unless anyone reports that combination doesn't work.

It still doesn't address why #530 is happening though.

**Comment by wartungsmonteur** [comment] 2023-09-13 18:28
Betrifft dieser Fehler mir die USB Variante ? Per TCP funktioniert es ohne Probleme.

**Comment by wills106** [comment] 2023-09-13 18:36
It can affect both, the Integration 2023.09.3 can downgrade your pyModbus to 3.3.1 even on HA 2023.9.x so it appears you don't have an issue.

But if your HA 2023.9.x forces pyModbus to 3.5.x that's when you have this issue.

So for example if you use the built in HA Modbus it requires 3.5.x on HA 2023.9.x and above. So using Integration 2023.09.3 becomes an issue. That's what Integration 2023.09.4b2 is trying to fix, getting all versions to cooperate.

**Comment by filipi992062** [comment] 2023-09-13 19:35
> > I updated to Home assistant 2023.9.2 this morning and the problem was solved.
> 
> @filipi992062 Are you on Solax 2023.09.3 or 2023.09.4b1?

Solax 2023.09.4b1

**Comment by Matz88** [comment] 2023-09-13 20:28
Also after upgrading to 2023.09.4b2 I unfortunately still have the same issue

**Comment by wills106** [comment] 2023-09-13 20:31
Have you tried:
Removing the Integration from the Integration page
Upgrading to 2023.09.4b2
Restarting HA
Re-adding the Integration?

**Comment by Matz88** [comment] 2023-09-13 22:23
being it already 2023.09.4b2, shall I first downgrade?

**Comment by Matz88** [comment] 2023-09-13 22:33
Tried with downgrade first, still some error, no entities loaded

**Comment by wills106** [comment] 2023-09-14 06:29
Just released [2023.09.4b3](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.09.4b3) which pins pyModbus to 3.5.2, it should help with people stuck on 3.3.1 etc.

**Comment by Matz88** [comment] 2023-09-14 07:55
Tried the beta 3 but still I have the same error:

File "/config/custom_components/solax_modbus/plugin_sofar.py", line 2430, in <module>
    order16 = Endian.Big,
              ^^^^^^^^^^

Is it still the same issue or something different?
I have also tried an HW reboot after upgrading. What else can I try?

**Comment by wills106** [comment] 2023-09-14 07:56
> order16 = Endian.Big,

I have found the error, I didn't convert all of those to Endian.BIG

Will push another update out.

**Comment by Matz88** [comment] 2023-09-14 07:57
Cool! Many thanks!

**Comment by wartungsmonteur** [comment] 2023-09-14 08:16
Das nenne ich Super Service, also dann spendiert alle mal dem guten Menschen auch ein paar Kaffee.

Grüße und Danke

**Comment by uspino2** [comment] 2023-09-14 08:38
Keep getting these errors with 4b4:

```
unrecognized Growatt_Modbus inverter type - firmware version : unknown
10:34:33 – (ERROR) SolaX Inverter Modbus (custom integration)
Growatt_Modbus: cannot find firmware version, even not for other Inverter
10:34:33 – (ERROR) SolaX Inverter Modbus (custom integration)
Growatt_Modbus: reading firmware number from address 0xbb9 failed; other address may succeed
10:34:33 – (WARNING) SolaX Inverter Modbus (custom integration)
Growatt_Modbus: reading firmware number from address 0x9 failed; other address may succeed
10:34:28 – (WARNING) SolaX Inverter Modbus (custom integration)
```

Reverting back to 2023.09.3 works for me (after a couple of reboots)

**Comment by wills106** [comment] 2023-09-14 08:41
How are you connecting? PocketWiFi, RS485-USB or RS485-Ethernet?

**Comment by uspino2** [comment] 2023-09-14 08:42
WaveShare RS485 TCP

**Comment by jamespreedy** [comment] 2023-09-14 08:44
> Das nenne ich Super Service, also dann spendiert alle mal dem guten Menschen auch ein paar Kaffee.
> 
> https://ko-fi.com/wills106
> 
> Grüße und Danke

Thanks for sharing ... beer money sent! 🍺

**Comment by Matz88** [comment] 2023-09-14 12:15
> Just released [2023.09.4b4](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.09.4b4) with the missing Endian.BIG from plugin_sofar and plugin_solax_a1j1

Perfect! Working like a charme

**Comment by wills106** [comment] 2023-09-15 05:24
Just released [2023.09.4b5](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.09.4b5) with further code cleanup.

**Comment by jamespreedy** [comment] 2023-09-15 05:50
@wills106 - issues resolved, I'm back up an running!
Thank you SO MUCH for all your help again. 🍺

**Comment by uspino2** [comment] 2023-09-15 06:04
For those of us who couldn't make 4b4 work, what would be the best installation process to get everything in the right order and pyModbus in the right version?

**Comment by wills106** [comment] 2023-09-15 06:37
> For those of us who couldn't make 4b4 work

b5 should work for you now, it's been tested on a Waveshare setup.

**Comment by mudshurko** [comment] 2023-09-15 14:05
I'm sorry
updated all to the latest b5
HA2023.9.2
with USB serial
restarted incl coldstart
2 x Solax X3 Hybrid G4 Master-Slave
get this 

Cleanup recv buffer before send: 0xaa 0x55 0xf 0xc8 0xff 0x1 0x1 0................

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for solax_modbus doing blocking calls at custom_components/solax_modbus/__init__.py, line 336: return self._client.read_holding_registers(address, count, **kwargs)

unrecognized inverter type - serial number : unknown

SolaX: cannot find serial number, even not for MIC

SolaX: reading serial number from address 0x300 failed; other address may succeed

Cleanup recv buffer before send: 0x60 0xea 0x0 0x0 0x0 0x4e 0x60 .........

SolaX: reading serial number from address 0x0 failed; other address may succeed

**Comment by mudshurko** [comment] 2023-09-16 06:51
hi
tried now to install pymodbus
 with
pip install -U pymodbus
but pip list will not list it after reboot
any recommendation how to run pymodbus?

**Comment by infradom** [comment] 2023-09-16 08:02
> hi tried now to install pymodbus with pip install -U pymodbus but pip list will not list it after reboot any recommendation how to run pymodbus?

I dont believe installing pymodbus manually is the way to go, especially since b5, we fixed the required version.
A hard restart of the HA hardware sometimes helps
You seem to have two inversters on the same modbus. I have no experience with the Master-Slave concept.
Which modbus addresses are used by both inverters ?

**Comment by wills106** [comment] 2023-09-16 08:18
> custom_components/solax_modbus/**init**.py, line 336: return self._client.read_holding_registers(address, count, **kwargs)

Even though you have downloaded 2023.09.4b5 you actually have 2023.09.4b4 code loaded there.
In 2023.09.4b5 than line of code is now at line 344

Remove the Integration from the Integration page and reconfigure it, it then should load the 2023.09.4b5 code.

**Comment by uspino2** [comment] 2023-09-18 06:55
Working perfectly with 2023.09.04. For those wanting to check HA pyModbus version in a VM environment, go to the console, then:
```
ha > login
# docker exec -it homeassistant /bin/bash
pip show pymodbus
```
As always, thank so much @wills106

**Comment by infradom** [comment] 2023-09-18 11:52
> Working perfectly with 2023.09.04. For those wanting to check HA pyModbus version in a VM environment, go to the console, then:
> 
> ```
> ha > login
> # docker exec -it homeassistant /bin/bash
> pip show pymodbus
> ```
> 
> As always, thank you so much @wills106

Thanks for this usefull instruction, I always forget how to execute commands in another container

**Comment by wills106** [comment] 2023-09-18 16:22
> Working perfectly with 2023.09.04. For those wanting to check HA pyModbus version

Thanks I have updated the Readme with the Info.

I'm going to close this issue down now as it seems to be resolved.

**Closed by wills106** 2023-09-18 16:22 UTC
Labels: bug, help wanted
