### ISSUE TITLE
[Bug]: growatt battery data is not displayed

### ISSUE THREAD

**Issue by iobrokerneu** [wills106/homeassistant-solax-modbus#749] opened 2024-02-17 09:27 UTC
### Describe the bug

Hello, I have installed the 2024.02.05 Beta 7 update. Unfortunately the data from the battery is not displayed. It's about the charge of the battery, the discharge of the battery and the display in %. greeting. I use a Growatt Mod 5000TL3-XH with an ARK HV battery
![IMG_7339](https://github.com/wills106/homeassistant-solax-modbus/assets/55629670/15fdf35b-7923-4df1-bfcc-235fa464991d)

### Integration Version

2024.2.1

### Homeassistant core version

2024.01.1

### Inverter brand

Growatt 

### Plugin used

plugin_growatt.py

### Serial prefix

JDM0DB

### Connection Method

USR TCP232-410S

**Comment by wills106** [comment] 2024-02-17 09:37
I'm closing this down as it's a duplicate of #718 which you have already raised.
Have a look at #735 as work is taking place on the MODxxKTL3-XH there.

**Closed** 2024-02-17 09:38 UTC
Labels: bug
