### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CristiXP** [wills106/homeassistant-solax-modbus#435] opened 2023-06-10 09:39 UTC
**Describe the bug**

**Mandatory details**
1. Integration Version:2023.06.5
2. HA Version:last
3. Inverter Brand:Solax Hybrid 15kW G4
4. Plugin Used: Solax Serial Modbus
5. First 6 digits of Serial:H34A15
6. Connection Method: TCP modbus

**Detailed Error Log**
Detailed Error Log, if you press on the individual error further information is displayed.
This is the content we need, the description alone doesn't provide enough context.

If there are no log's showing for SolaX try the following depending on your language settings, you can find the full logs under:

Settings → System → Logs > at bottom of page press “LOAD FULL LOGS”

Now the full logs are loaded. If you scroll down, you will see them.
Once the full logs are shown, you can either use the search function in your browser to search for “solax” related entries or use the search entry field on top of the page.

Search for

solax

and report us the logs. Make sure to replace sensitive information by xxxx (if any)

**Additional context**

It seems that on the last updates, tough I have selected in the integration to poll every 5 sec, it still polls every 30 sec. Selected 10 sec, but still it does every 30 sec. Any ideea how to fix this? In the past it worked... not sure from what version the issue appeared.

Thank you,

Cristian

**Comment by wills106** [comment] 2023-06-10 09:47
This is a duplicate of #434

**Closed by wills106** 2023-06-10 09:47 UTC
