### ISSUE TITLE
[Bug]: Missing firmware sensors after 2024.05.7

### ISSUE THREAD

**Issue by ivankarpov** [wills106/homeassistant-solax-modbus#913] opened 2024-05-28 12:13 UTC
### Describe the bug

the following sensors are missing:

sensor.solax_bootloader_version
sensor.solax_firmware_version_modbus_tcp_major
sensor.solax_firmware_version_modbus_tcp_minor
sensor.solax_inverter_arm_firmware_major_version
sensor.solax_inverter_arm_firmware_minor_version
sensor.solax_inverter_dsp_firmware_major_version
sensor.solax_inverter_dsp_firmware_minor_version
sensor.solax_inverter_dsp_hardware_version

### Integration Version

2024.05.7

### Homeassistant core version

2024.5.5

### Inverter brand

Solax

### Plugin used

plugin_solax.py

### Serial prefix

H4752

### Inverter firmware versions

ARM 1.40 DSP 1.43

### Connection Method

Solax Pocket wifi 3

### Dongle firmware

n/a

**Comment by wills106** [comment] 2024-05-28 13:19
The important ones are displayed in the "Device info" panel as per [2024.05.4](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.05.4)

Duplicate of #909

**Closed by wills106** 2024-05-28 13:19 UTC
Labels: bug, solax

**Comment by wills106** [comment] 2024-07-03 08:11
Device info has live sensors in [2024.07.0b1](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.07.0b1)
